/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://s6inlb5ynvdqvhcrzq6pglfw6a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-e5ftohnasnbxxhgrhh2uysoazu",
    "aws_cognito_identity_pool_id": "us-east-1:6a41f238-32e8-4651-9393-4ec5e9632985",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BZhRszohb",
    "aws_user_pools_web_client_id": "4uuikqsdh9fgq4jpss4dgfb6f8",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 12,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "timanderic-storage-a587c09210046-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
